---
title: "Running"
format: html
---

# Beginnings

For as long as I can remember, I have been involved in all kinds of sports. Despite not having much success in soccer and baseball, they set a strong competitive baseline in me. In my sophomore year of high school, I joined the track team where my perfect attendance at practices and consistent work led to tangible results and two captain roles by my senior year. I really cherished my short three years with the team, but I left with a desire to achieve more after a frustrating senior year.

I started consistently running just before I left home and community college to start my years at UC Santa Barbara. I was not running as fast as thirteen-year-old me, but it was the form of exercise I enjoyed most. Having the North Campus Open Space and Elwood as my backyard really contributed to the consistent training I was able to attach myself to. 

Social media discourse in 2025 about a running influencer (https://www.thecut.com/article/tiktok-controversy-kate-mackz-karoline-leavitt-interview.html) collaborating with the White House Press Secretary brought massive attention to how interconnected running and politics are. An administration that guts clean air regulations (https://www.pbs.org/newshour/politics/epa-head-announces-sweeping-plan-to-revoke-dozens-of-environmental-regulations), cuts programs that provide healthy food to kids (https://www.edweek.org/policy-politics/trump-admin-cuts-program-that-brought-local-food-to-school-cafeterias/2025/03), and targets transgender athletes (https://williamsinstitute.law.ucla.edu/publications/impact-trans-sports-ban-eo/), should not be welcomed by the running community. It made me further realize how much of a privilege it is to run with access to adequate food and gear. The environmental studies community and I must understand these connections and fight for access to healthy food, clean air, and inclusion of all athletes. 
